on:
  push:
    tags:
      - "release:*"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release and Upload JAR
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}