on:
  push:
    tags:
      - "release:*"
      - "v*"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release and Upload JAR
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/*.jar
          body_path: .github/ChangeLog.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}